import Head from 'next/head';
import React, { useState } from 'react';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import Portfolio from '../../components/Portfolio';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';

export default function PortfolioPage() {
  const [active, setActive] = useState('all');
  const [itemShow, setItemShow] = useState(7);
  const portfolioData = [
    {
      title: 'НБТ 312 - 313',
      href: '/case-study-details8',
      src: 'https://img3.akspic.ru/crops/3/9/0/7/6/167093/167093-toronto-poezd-zdanie-avtomobilnoe_osveshhenie-neboskreb-3840x2160.jpg',
    },
    {
      title: 'меҳнатни мухофаза қилиш тўғримидаги қонун',
      href: '/case-study-details9',
      src: 'https://img1.akspic.ru/crops/5/5/3/5/5/155355/155355-zheleznodorozhnyj_transport-poezd-avtomobilnoe_osveshhenie-podvizhnoj_sostav-transportnyj_uzel-3840x2160.jpg',
    },
    {
      title: 'Шахсий ҳимоя воситалари',
      href: '/case-study-details10',
      src: 'https://img3.akspic.ru/crops/3/4/5/6/5/156543/156543-zheleznodorozhnye_puti_v_snegu-poezd-zheleznodorozhnyj_transport-sneg-trek-3840x2160.jpg',
    },
    {
      title: 'Талон тизими',
      href: '/case-study-details11',
      src: 'https://img2.akspic.ru/crops/1/2/5/8/3/138521/138521-obshhestvennyj_transport-elektrichestvo-poezd-zheleznodorozhnyj_transport-noch-3840x2160.jpg',
    },
    {
      title: 'Янгиликлар',
      href: 'https://lex.uz/',
      src: 'https://img2.akspic.ru/crops/3/7/9/9/4/149973/149973-zheleznodorozhnyj_vagon-elektrichestvo-vozdushnoj_linii_elektroperedach-zheleznodorozhnyj_transport-zheleznodorozhnyj_vokzal-3840x2160.jpg',
    },
  ];
  return (
    <>
      <Head>
        <title>Nizom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Div className="container">
          <Div className="cs-portfolio_1_heading">
            <Div className="cs-filter_menu cs-style1">
            </Div>
          </Div>
          <Spacing lg="90" md="45" />
          <Div className="row">
            {portfolioData.slice(0, itemShow).map((item, index) => (
              <Div
                className={`${
                  index === 3 || index === 6 ? 'col-lg-8' : 'col-lg-4'
                } ${
                  active === 'all'
                    ? ''
                    : !(active === item.category)
                    ? 'd-none'
                    : ''
                }`}
                key={index}
              >
                <Portfolio
                  title={item.title}
                  subtitle={item.subtitle}
                  href={item.href}
                  src={item.src}
                  variant="cs-style1 cs-type1"
                />
                <Spacing lg="25" md="25" />
              </Div>
            ))}
          </Div>

          <Div className="text-center">
            {portfolioData.length <= itemShow ? (
              ''
            ) : (
              <>
                <Spacing lg="65" md="40" />
              </>
            )}
          </Div>
        </Div>
      </Layout>
    </>
  );
}
