import Head from 'next/head';
import React from 'react';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function About() {
  const funfaceData = [
  ];
  return (
    <>
      <Head>
        <title>Ximoya vositalari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Maxsus kiyim"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Maxsus kiyim ( ish kiyimi , kombinezon ) - bu ish joyidagi xodimlarning sog'lig'i uchun zararli va xavfli omillardan himoya qilish uchun mo'ljallangan shaxsiy himoya vositalari .
                <br />
                Ba'zi hollarda, maxsus kiyim ish beruvchilar tomonidan korporativ uslub elementlari bilan bog'lanish orqali yakuniy iste'molchilar va xususiy investorlar bilan aloqa vositasi sifatida ko'rib chiqilishi mumkin.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator white-bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            
            <Div className="col-lg-7 shv">
              <img
                src="https://img.freepik.com/free-vector/work-wear-uniform-set_1284-68407.jpg?w=900&t=st=1715858522~exp=1715859122~hmac=4a99ee08591236deff3e3e4995065e2a07088801e0611aed54ba446294cc7072"
                alt="About"
                className="cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-7 shv">
              <img
                src="https://prouniforma.uz/upload/iblock/8c0/yiv49iwpz6okqtta03kp9u5rcmpswsce.jpg"
                alt="About"
                className="cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Maxsus bosh kiyim"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Yuqori zichlikdagi polipropilendan (PP), ultrabinafsha nurlanishiga chidamli, sozlanishi ventilyatsiyali xavfsizlik dubulg'asi. Poliamid interyeri: 8 ta biriktirma nuqtasi bo'lgan 3 ta to'qimachilik tasmasi. Bosh bandining old qismidagi terni yutuvchi qo'shimcha. <br /> Ko'zoynak, minigarnituralar, qalqonlarni ulash uchun cho'ntaklar. ROTOR® innovatsion mahkamlash tizimi yordamida bosh atrofi 53 dan 63 sm gacha sozlanishi. 
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator white-bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>

        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Dielektrik qulqoplar"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Dielektrik qo'lqoplar qo'llaringizni elektr toki urishidan himoya qilish uchun mo'ljallangan. 1000 V gacha bo'lgan elektr inshootlarida ishlaganda, asosiy elektr himoya vositasi sifatida qo'lqop ishlatiladi, 1000 V dan yuqori elektr inshootlarida esa qo'shimcha sifatida ishlatiladi. <br /> Elektr qurilmalarida uzluksiz lateks qo'lqoplardan foydalanishga ruxsat beriladi (GOST 12.4.183-91 va TU 38.306-5-63-97 ga muvofiq) yoki pichoq bilan ishlangan plastmassa kauchukdan tikilgan qo'lqoplardan foydalanish mumkin (TU 38305-05-257-89 ga muvofiq).
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator white-bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            
            <Div className="col-lg-7 shv">
              <img
                src="https://ikarvon.uz/storage/products/January2022/35883/251.jpg"
                alt="About"
                className="cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-7 shv">
              <img
                src="https://static.tildacdn.com/tild3937-3037-4933-b565-373830633530/___18.png"
                alt="About"
                className="cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Maxsus oyoq kiyim"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  This is the main factor that sets us apart from our
                  competition and allows us to deliver a specialist business
                  consultancy service. Our team applies its wide-ranging
                  experience to determining. Through our years of experience,
                  we’ve also learned that while each channel.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator white-bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            
            
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Tok o'tqazmaydigan gilam"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Dielektrik paspaslar kuchlanishi 1000 V dan oshmaydigan yopiq turdagi elektr inshootlarida, shuningdek quruq ob-havo sharoitida ochiq turdagi elektr inshootlarida qo'shimcha himoya qilish uchun ishlatiladi. Binolar nam yoki chang bo'lmasligi kerak. <br />
                Paspaslar elektr tokining kuchlanishi bo'lgan qismlar bilan aloqa qilish imkoniyati mavjud bo'lgan uskunalar oldida, ta'mirlashga texnik xizmat ko'rsatish vaqtida, yig'ilishlar va kommutatorlar, generatorlar, dvigatellar va boshqalar oldida joylashtiriladi.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator white-bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-7 shv">
              <img
                src="https://grandalliance.uz/thumb/2/5d0am2TRiWl9v6dNPtlsjw/r/d/2021-02-05-17-01-21-014267-d213c5da24ca77f329e2fa9f3950831e.jpg"
                alt="About"
                className="cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
          </Div>
        </Div>
      </Layout>
    </>
  );
}
