import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўзининг эҳтиётсизлиги ва технологик жараён талаблари риоя этмаслик"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 07 февраль куни соат 00-10 лар атрофида машинист Р.М.Махамаджонов ва машинист ёрдамчиси С.С.Собиржоновлар бошқарувидаги ТЭМ-2 русумли 6773-рақамли манёвр тепловози Келес станциясининг 6-йўлидан 8-йўлга 1 дона 29079845-рақамли усти ёпиқ вагонни олиб кириш бўйича манёвр ишларини бажарган. Манёвр вақтида вагоннинг ҳаракат йўналиши бўйлаб бош томонининг ўнг томонидаги зинада осилиб кетаётган “Тошкент МТУ” УКга қарашли “Келес” станцияси бош кондуктори Суннатов Даврон Турғун ўғли (Тошкент вилояти, Тошкент туманида 07.02.1992 йил туғилган, оилали 2 нафар фарзанди бор, иш стажи 2012 йилдан) 8-йўлнинг ёнидаги юкларни ортиш-тушириш платформасига яқинлашганида 29079845-рақамли усти ёпиқ вагон ва платформа орасига қисилиб қолиб оғир тан жароҳатини олган. Машинист Р.М.Махамаджонов ва машинист ёрдамчиси С.С.Собиржоновлар томонидан бош кодуктор Д.Т.Суннатовга биринчи тиббий ёрдам кўрсатиб, шошилинч тез тиббий ёрдамга қўнғироқ қилишган. Бош кондуктор Д.Т.Суннатов Тошкент шаҳар Ибн Сино номли 1-сонли касалхонага ётқизилган. Шифокорлар томонидан ўнг сон суяги ёпиқ синиши, икки томонлама қов ва ўтиргич суяги синиши ташҳиси қўйилган. Воқеа тафсилотлари ўрганилмоқда.
          </p>
        </Div>
      </Layout>
    </>
  );
}
