import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Гуруҳи (оғир ва енгил ҳолат) автоҳалокат"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 26 март куни тахминан 16-30 лар атрофида Дарбанд темир йўл масофаси ҳайдовчиси Эронов Отабек Оллоқулович бошқарувида бўлган давлат рақами 75326 UAA  TAYOTA русумли автотранспорт М39 йўлининг 1337 кмда ҳаракатланиб келаётган ISUZU юк машинасига келиб урилиши оқибатида автоҳалокат рўй берган, TAYOTA русумли автотранспортда бўлган корхона бош ҳисобчиси, С.Х.Жураев, омборхона мудири З.Б.Бойқобилов устахона техниги З.З.Холмуминовларга биринчи тиббий ёрдам кўрсатилиб, Бойсун туман тез тиббий ёрдам шифохонасига олиб борилган. Шулардан О.О.Эронов ва З.Б.Бойқобилов-ларнинг аҳволи яхши бўлганлиги сабабли уйига жавоб берилган. Бойсун тумани тиббиёт бирлашмаси реанимация бўлими даволовчи шифокор томонидан 2024 йил 27 март куни берилган ташхисида  С.Х.Жураевнинг (Сурхандарё вилояти, Бойсун туманида 1964 йил 26 сентябрида туғилган, оилали 4 нафар фарзанди бор, маълумоти олий, темир йўл масофасида иш стажи 2008 йилдан) бош мия лат ейиши, ўнг сон суягидан очиқ синиш ва З.З.Холмуминовнинг (Сурхандарё вилояти, Бойсун туманида 1968 йил 10 февралида туғилган, оилали 3 нафар фарзанди бор, маълумоти ўрта-махсус, темир йўлда иш стажи 2007 йилдан) бош мия лат ейиши, бош пешонасида йиртилган жароҳат борлиги кўрсатилган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
