import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Меҳнат муҳофазаси ва техника хавфсизлиги
          қоидаларига риоя қилмаслик ва ўзининг эҳтиётсизли-ги  
          "
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 12 март куни тахминан 16-00 лар атрофида Жарқўрғон станциясида №6607 рақамли манёвр тепловозининг аккумулиятор батарияларини камера эшиги очилиб кетганлигини кўриб, камера эшигини ёпиш мақсадида машинист Умаров Алижон Мирзокулович (Сурхандарё вилояти, Жарқўрғон туманида 1975 йил 15 февралида туғилган, оилали 5 нафар фарзанди бор, маълумоти ўрта-махсус, иш стажи 2005 йилдан) билан ҳолати оғир бахтсиз ҳодиса содир бўлган. Тепловоз (плошадка) майдончасига чиқган ва ёмғир ёғиб турганлиги сабабли, тепловоз (плошадка) майдончаси сирпанчиқ ҳолатга келиб қолганлиги учун оёғи тойиб кетиши натижасида чап қўл елка қисмидан тан жароҳати олган. Зудлик билан А.М.Умаровга биринчи тиббий ёрдам кўрсатилиб, Жарқурғон туман тез тиббий ёрдам шифохонасига олиб борилган. Воқеа тафсилотлари ўрганилмоқда.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
