import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўрта оғир"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 14 апрел куни тахминан соат 15-40 лар атрофида йул созловчиси Бекмуратов Абат Ережепович (Қорақалпоғистон Республикаси Шуманай туманида 1973 йил 19 сентябрда туғилган, маълумоти ўрта, оилали 3 нафар фарзанди бор, темир йўлда иш сажи 2020 йилдан) билан холати ўрта оғир бахтсиз ходиса содир бўлган. 
          279-сонли Йул машина станцияси йул созловчиси А.Е.Бекмуратов Ургенч-Ханка стаициялари оралиғи 392 км 7-В ПКда темир панжаралари тўсиқлар ўрнатиш вақтида, металл тўсиқ устуни бетон қоришмасини тайёрлаш учун йўл созловчилар А.Е.Бекмуратов ва Жаксиликовлар насилка билан шағал ташиш вақтида А.Е.Бекмуратов ўз эхтиётсизлиги туфайли йиқилиб ўнг оёғидан жарохат олган ва унга биринчи тиббий ёрдам кўрсатилиб, Урганч шахри шифохонасига олиб борилган. Шифокорлар томонидан берилган ташхисига кўра А.Е.Бекмуратовни ўнг оёғи 5-панжа суяги проксимол охиридан ёпиқ синиши деб хулоса берилган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
