import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўрта бўғин раҳбарлари-нинг ўз вазифасига масъулиятсиз-лиги, Электр хавфсизлиги ва технологик жараён талабларига риоя этмаслик"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 20 март куни Сирдарё ЭЧК-7 бошлиғи Шохрух Турсунов, иш раҳбари (руководитель работ) электромеханик Рашид Умаралиев бошчилигидаги бригада аъзолари электромонтёрлар Мансур Бобомуродов, Зохид Бекболаев, ҳайдовчи Акмал Қодировларни Оқолтин-Гулистон перегони 3484 километрнинг 5-чи пикетидаги ЛЭП ПЭ-10 кВ линияси 9/2-сонли сигнал нуқтасида носоз ОМ-1,25 кВА турдаги қувватли трансформатор (однофазный маслянный трансформатор) энергодиспетчер Жасур Қобуловнинг 924-сонли буйруғига асосан алмаштириш учун кечаси соат 19-53 да ишга рухсат берилган. ОМ-1,25 ни алмаштириш учун электромеханик  Бобомуродов Мансур Усмонқул ўғли (1996 йил 26 феврал куни Сирдарё вилояти, Сирдарё туманида  туғилган, маълумоти олий, оилали, 1 нафар фарзанди бор, темир йўлдаги иш стажи 2019 йилдан) 3 (уч) дона ерлатгич штангаларини улаган, шундан бир дона трансформаторни юқорисидаги металл конструкцияга ва икки дона ерлатгични штангани ПКМ (предохранительная конструкция) юқорисига илган. Тахминан кечаси соат 21-30 да ОМ-1,25 ни алмаштириш якунлангандан сўнг, ерлатгич штангаларини электромеханик М.У.Бобомуродов ўзига нисбатан узоқда илинган ерлатгич штангани ечиб, сўнгра ёнида илинган ерлатгич штангани ечиб пастга тушмоқчи бўлганда контакт тармоғида йўналтирилган кучланиш пайдо бўлиб (наведённое напряжение), тана қисмига тегиб кетиши оқибатида кучланиш таъсирига тушиб қолган ва жароҳатланиш натижасида воқеа жойида вафот этган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
