import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Оғир"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          2024 йил 15 апрел куни тахминан тунги соат 02-45 лар атрофида Тепловозларни таъмирлаш цехи чилангари Холмаматов Эгамназар Насимович (Қашқадрё вилояти, Қарши туманида 1965 йил 09 декабрда туғилган, маълумоти ўрта, оилали 4 нафир фарзанди бор, темир йўлда иш стажи 1987 йилдан) билан ҳолати оғир бахтсиз ҳодиса содир бўлган. Кечги сменага Тепловозларни, таъмирлаш цехи чилангари Э.Н.Холмаматов навбатчилик жадвалига асосан иш жойига келган ва цех устаси Б.Рахматов томонидан жорий йўл-йўриқ ўтказилиб ишга қўйилган. Тепловозларни таъмирлаш цех устаси Раҳматов Бобур томонидан чилангар Э.Н.Холмаматов 2ТЕ10М русумли №0236 рақамли тепловознинг Б бўлинмасидаги иккинчи босқичли ҳаво ҳайдагични текшириш вазифаси топшириғини олган ва иш бошлаган. Тахминан соат 02:45 лар атрофида Тепловоз устига чиқиб иккинчи босқичли ҳаво ҳайдагични текшириб носозликни бартараф этгандан сўнг том қисмини ёпаётган вақтида ўзининг эҳтиётсизлиги сабабли оёғи сирпаниб кетиши натижасида тахминан 3,5 м - 4 м баландликда полга йиқилиб тушган ва тан жароҳати олган. Иш жойида биринчи тиббий ёрдам кўрсатилиб Қарши локомотив депоси навбатчилик қисми машинасида уста Б.Раҳматов томонидан Республика шошилинч тиббий ёрдам илмий маркази Кашқадарё филиалига олиб борилган. Шифокорларнинг хулосасига кўра чап томон кўплаб қовурғаларнинг синиши ташхиси қўйилган. 
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
