import { useState, useRef } from 'react';
import Head from 'next/head';
import React from 'react';
import emailjs from '@emailjs/browser';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';
import ContactInfoWidget from '../components/Widget/ContactInfoWidget';

export default function Contact() {
  const form = useRef();
  const [showSuccessPopup, setShowSuccessPopup] = useState(false);

  const sendEmail = (e) => {
    e.preventDefault();
  
    // Проверка на заполнение обязательных полей
    const formData = new FormData(form.current);
    let hasEmptyFields = false;
  
    formData.forEach((value, key) => {
      if (!value.trim()) {
        hasEmptyFields = true;
        const field = form.current.querySelector(`[name="${key}"]`);
        field.classList.add('empty-field');
      }
    });
  
    // Если есть пустые обязательные поля, не отправляем письмо и показываем сообщение об ошибке
    if (hasEmptyFields) {
      console.log('Пожалуйста, заполните все обязательные поля.');
      return;
    }
  
    // Отправляем форму только если нет пустых обязательных полей
    emailjs
      .sendForm('service_tdslx9v', 'template_26kqadd', form.current, {
        publicKey: '1APw6gCePaAFXV3yB',
      })
      .then(
        () => {
          console.log('УСПЕХ!');
          setShowSuccessPopup(true);
        },
        (error) => {
          console.log('ОШИБКА...', error.text);
        },
      );
  };
  

  const handleClosePopup = () => {
    setShowSuccessPopup(false);
    window.location.reload(); // Обновляем страницу после закрытия всплывающего окна
  };

  return (
    <>
      <Head>
        <title>Murojatlar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Div className="bg-1">
          <Div className="container">
            <Div className="row">
              <Div className="col-lg-6">
                <SectionHeading
                  title="Bizning manzil!"
                  subtitle=""
                />
                <Spacing lg="55" md="30" />
                <ContactInfoWidget withIcon />
                <Spacing lg="0" md="50" />
              </Div>
              <Div className="col-lg-6">
                <form ref={form} onSubmit={sendEmail} className="row">
                  <Div className="col-sm-6">
                    <label className="cs-primary_color">F.I.O</label>
                    <input type="text" name="to_name" className="cs-form_field" />
                    <Spacing lg="20" md="20" />
                  </Div>
                  <Div className="col-sm-6">
                    <label className="cs-primary_color">Korxonangiz</label>
                    <input type="text" name="from_name" className="cs-form_field" />
                    <Spacing lg="20" md="20" />
                  </Div>
                  <Div className="col-sm-6">
                    <label className="cs-primary_color">Telefon raqamingiz</label>
                    <input type="mobile" className="cs-form_field" name="to_number"/>
                    <Spacing lg="20" md="20" />
                  </Div>
                  <Div className="col-sm-12">
                    <label className="cs-primary_color">Murojatni kiriting</label>
                    <input
                      cols="60"
                      rows=""
                      className="cs-form_field" type="text" name="message"
                    />
                    <Spacing lg="25" md="25" />
                  </Div>
                  <Div className="col-sm-12">
                    <button type='submit' className="cs-btn cs-style1">
                      Yuborish
                    </button>
                  </Div>
                </form>
              </Div>
            </Div>
          </Div>
        </Div>
        {showSuccessPopup && (
          <Div className="popup-overlay">
            <Div className="popup">
              <p>Malumotlar qabul qilindi</p>
              <button onClick={handleClosePopup}>OK</button>
            </Div>
          </Div>
        )}
        <Div className="cs-google_map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10624.365533206606!2d64.54371445445497!3d39.72342174022735!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f501d22b10c61b7%3A0x309f33e3bdc5fea7!2sBuxoro%20MTU%20UK!5e0!3m2!1sen!2s!4v1715745340442!5m2!1sen!2s"
            allowFullScreen
            title="Google Map"
          />
        </Div>
        <Spacing lg="50" md="40" />
      </Layout>
    </>
  );
}
