import Head from 'next/head';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import MovingText from '../components/MovingText';
import Spacing from '../components/Spacing';

export default function Home() {
  // Hero Social Links
  const heroSocialLinks = [
    // {
    //   name: 'Behance',
    //   links: '/',
    // },
    // {
    //   name: 'Twitter',
    //   links: '/',
    // },
  ];

  // FunFact Data
  const funfaceData = [
    {
      title: 'Global Happy Clients',
      factNumber: '40K',
    },
    {
      title: 'Project Completed',
      factNumber: '50K',
    },
    {
      title: 'Team Members',
      factNumber: '245',
    },
    {
      title: 'Digital products',
      factNumber: '550',
    },
  ];

  return (
    <>
      <Head>
        <title>E - TB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero
          title="E - TB "
          subtitle="Bizning maqsadimiz - har bir xodim xavfsizligidir"
          btnLink=""
          scrollDownId="#service"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="https://w.forfun.com/fetch/7a/7adb5ce5e116ca91251a4ef6d147287e.jpeg"
        />
        <Spacing lg="125" md="70" />
        <MovingText text="Sizning hayotingiz biz uchun muhim" />
        <Spacing lg="105" md="70" />
      </Layout>
    </>
  );
}
